### ISSUE TITLE
loginEndpoint

### ISSUE THREAD

**Issue by rhebert24** [foluis/Salesforce_PushTopics#2]
loginEndpoint example values missing from App.config
Code references loginEndpoint in SalesforceOauth.cs but the App.config contains no such value.
Am i missing something?
Not sure what URL is needed for this. Can you give a example ? Since i think its different than the streaming url.

**Comment by timhodgson** [comment]
Same issue here.  Anyone find the answer to this?

**Comment by foluis** [comment]
When you conect to salesfore you use https://login.salesforce.com/ o a sandbox for testing, so those values are the ones that you are supose to put there.
